### ISSUE TITLE
Map out Sleep.js

### ISSUE THREAD

**Issue by Corbinj22** [nickstaylor/refactor-tractor#25]
- [ ] Sleep.js

**Comment by rachael-t** [comment]
Notes from mapping:
<img width="661" alt="Screen Shot 2020-04-08 at 3 36 11 PM" src="https://user-images.githubusercontent.com/54180641/78836176-cd11fd00-79ae-11ea-92c2-18068059acc6.png">
<img width="687" alt="Screen Shot 2020-04-08 at 3 36 24 PM" src="https://user-images.githubusercontent.com/54180641/78836180-cedbc080-79ae-11ea-8cab-20a210fa6caa.png">
